# Generated by Django 4.1.5 on 2023-01-31 11:10

import common.utils.text
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('made_in', models.CharField(blank=True, max_length=100, null=True)),
                ('specification', models.CharField(blank=True, max_length=100, null=True)),
                ('manufactured', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('sub_category', models.CharField(max_length=100)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='products/%Y/%m/%d')),
                ('alt', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specifications_code', models.CharField(blank=True, default=common.utils.text.create_new_ref_number, editable=False, max_length=10, unique=True)),
                ('instruction', models.CharField(blank=True, max_length=600, null=True)),
                ('warning', models.CharField(blank=True, max_length=600, null=True)),
                ('expiration', models.DateField(blank=True, null=True)),
                ('diminution', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('color', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=100, null=True)),
                ('application', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Store_branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppliers', models.CharField(blank=True, max_length=100, null=True)),
                ('store_name', models.CharField(blank=True, max_length=100, null=True)),
                ('branch', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('location', models.URLField(blank=True, db_index=True, max_length=128, unique=True)),
                ('shelf_no', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppliers', models.CharField(blank=True, max_length=300, null=True)),
                ('product_name', models.CharField(blank=True, max_length=300, null=True)),
                ('part_number', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.PositiveSmallIntegerField(default=1)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True, max_length=2000, null=True)),
                ('barcode', models.ImageField(blank=True, upload_to='barcodes/')),
                ('tags', models.CharField(blank=True, choices=[(None, '--Please choose--'), ('sell', 'sell'), ('Hot', 'Hot'), ('Fast moving', 'Fast moving')], max_length=30, null=True)),
                ('label', models.CharField(blank=True, choices=[(None, '--Please choose--'), ('Bast seller', 'Bast seller'), ('AutoZoom Choice', 'AutoZoom Choice'), ('New', 'New')], max_length=30, null=True)),
                ('return_police', models.CharField(blank=True, choices=[(None, '--Please choose--'), ('No Return', 'No Return'), ('same day', 'same day'), ('seven days', 'seven days'), ('Fifteen(15) days', 'Fifteen(15) days'), ('Thirty(30) days', 'Thirty(30) days')], max_length=30, null=True)),
                ('states', models.CharField(blank=True, choices=[(None, '--Please choose--'), ('new brand', 'new brand'), ('Open box', 'Open box'), ('used', 'used'), ('like New', 'like new')], max_length=30, null=True)),
                ('available', models.BooleanField(default=True)),
                ('slug', models.SlugField(editable=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('update', models.DateField(auto_now=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category')),
                ('images', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='store.images')),
                ('specification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.specification')),
                ('stores', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store_branch')),
            ],
        ),
    ]
