# Generated by Django 4.1.5 on 2023-02-06 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_brand_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store_branch',
            name='shelf_no',
        ),
        migrations.AddField(
            model_name='products',
            name='shelf_no',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
