# Generated by Django 4.1.5 on 2023-02-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_store_branch_shelf_no_products_shelf_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='shipping',
            field=models.CharField(blank=True, choices=[(None, '--Please choose--'), ('new brand', 'new brand'), ('Open box', 'Open box'), ('used', 'used'), ('like New', 'like new')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='states',
            field=models.CharField(blank=True, choices=[(None, '--Please choose--'), ('Free', 'Free'), ('Not Free', 'Not Free'), ('on Stor pickup', 'on Stor pickup'), ('Buy 5+ get free', 'Buy 5+ get free'), ('let you know on checkout', 'let you know on checkout')], max_length=30, null=True),
        ),
    ]
