# Generated by Django 4.1.5 on 2023-02-23 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_images_created_alter_products_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='off_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
