# Generated by Django 4.1.5 on 2023-02-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_products_off_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='discount',
            new_name='discount_present',
        ),
        migrations.AddField(
            model_name='products',
            name='profit_present',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
