# Generated by Django 4.1.5 on 2023-02-23 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_images_created_alter_products_shipping'),
        ('cart', '0002_alter_cartitem_price_ht_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='update',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='update',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='price_ht',
        ),
        migrations.AddField(
            model_name='cart',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_item', to='cart.cart'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_product', to='store.products'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
